### ISSUE TITLE
Prefer core url module over RegExp'ing

### ISSUE THREAD

**Issue by boennemann** [eHealthAfrica/kazana-bootstrap#5]
Even if it's just for readability :) 

https://github.com/eHealthAfrica/kazana-bootstrap/blob/master/index.js#L54

**Comment by jo** [comment]
Even better:
```js
  requestDefaults: {
    auth: {
      user: 'admin',
      pass: 'admin'
    }
  }
```

But this is currently blocked by [an issue in couchdb-bootstrap](https://github.com/eHealthAfrica/couchdb-bootstrap/issues/28)
